Feature/async download
Magic-Pod/magic-pod-api-client pull request #12
Opened 2022-01-11 00:35 UTC by nkns165

Now screenshots are acquired by new endpoints for async download.

2022-01-11 08:38 UTC, NozomiIto requested changes

2022-01-11 08:38 UTC, NozomiIto commented on common/common.go
> +			print(".")
- If GetBatchTaskStatus returns something unexpected, I think an exception should be thrown rather than infinite loop.

2022-01-11 08:38 UTC, NozomiIto commented on common/common.go
> +	for {
I think this loop should thrown an error after specific amount of time, to avoid infinite loop.

2022-01-12 02:12 UTC, nkns165 commented on common/common.go
> +			print(".")
Fixed so that `print(".")` is executed only for status "running", and an error is throw for other status.

2022-01-12 02:12 UTC, nkns165 commented on common/common.go
> +	for {
Added timeout option.

2022-01-12 03:43 UTC, NozomiIto approved these changes

2022-01-12 03:44 UTC, merged